# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-19 20:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adverts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_created', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430 \u0441\u043e\u0437\u0434\u0430\u043d\u0438\u044f')),
                ('date_modified', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u0414\u0430\u0442\u0430 \u0438\u0437\u043c\u0435\u043d\u0435\u043d\u0438\u044f')),
                ('body', models.TextField()),
            ],
            options={
                'verbose_name': '\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u0435',
                'verbose_name_plural': '\u041e\u0431\u044a\u044f\u0432\u043b\u0435\u043d\u0438\u044f',
            },
        ),
        migrations.CreateModel(
            name='Knowledges',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=250, verbose_name='\u0423\u043c\u0435\u043d\u0438\u0435')),
                ('skill_level', models.IntegerField(default=0, help_text='\u041e\u0446\u0435\u043d\u043a\u0430 \u0441\u0432\u043e\u0438\u0445 \u0437\u043d\u0430\u043d\u0438\u0439 \u043f\u043e \u044d\u0442\u043e\u043c\u0443 \u043f\u0440\u0435\u0434\u043c\u0435\u0442\u0443 \u043f\u043e \u0448\u043a\u0430\u043b\u0435 \u043e\u0442 0 \u0434\u043e 10', verbose_name='\u0423\u0440\u043e\u0432\u0435\u043d\u044c')),
            ],
            options={
                'verbose_name': '\u0417\u043d\u0430\u043d\u0438\u0435',
                'verbose_name_plural': '\u0417\u043d\u0430\u043d\u0438\u044f',
            },
        ),
        migrations.AddField(
            model_name='adverts',
            name='i_can',
            field=models.ManyToManyField(related_name='skill_name2', to='core.Knowledges', verbose_name='\u042f \u0443\u043c\u0435\u044e'),
        ),
        migrations.AddField(
            model_name='adverts',
            name='i_want',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skill_name1', to='core.Knowledges', verbose_name='\u042f \u0445\u043e\u0447\u0443 \u043d\u0430\u0443\u0447\u0438\u0442\u044c\u0441\u044f'),
        ),
    ]
